name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTFLAGS: -D warnings

jobs:
  clippy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --check
      - run: cargo clippy

  build:
    needs: clippy
    strategy:
      fail-fast: false
      matrix:
        triple: ["x86_64-unknown-linux-musl", "aarch64-unknown-linux-musl"]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: build ${{ matrix.triple }}
    steps:
      - uses: cachix/install-nix-action@v31
      - uses: actions/checkout@v4
      - run: nix build ".#cross-${{ matrix.triple }}"
      - uses: actions/upload-artifact@v4
        with:
          name: wolly-${{ matrix.triple }}
          path: result/bin/wolly
